# Generated by Django 5.1.7 on 2025-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corex_workout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="workouts/photos/"
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="workouts/videos/"),
        ),
    ]
