# Generated by Django 5.1.7 on 2025-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corex_workout", "0002_workoutplan_photo_workoutplan_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutplan",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="workoutplan",
            name="video",
        ),
        migrations.AddField(
            model_name="exercise",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="workouts/videos/"),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="workouts/images/"
            ),
        ),
    ]
