# Generated by Django 5.1.7 on 2025-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corex_diet", "0002_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="meals/"),
        ),
    ]
